language: node_js
node_js:
- '8'
before_install:
 - npm i npm-cli-login -g
 - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
 - npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "LeLPY1+zUIfr/HuPp4rGjtFJM5wMmMuVgQJcO7ltLw9b9j2L+MSDqJhb02SKptOoW+stq9KFGh5XC8KthAoM6s9Tfc9fa+moSfSGmsLQLFbemZmq4VGMA0HbFYjbkqcK1p83R+e+FnBDR94ApKmC3mNcMdrr8YkjBDGKAG4qgvZpNvkhP3xJEY9Y5pZ721n9Q6V/LqbFiAyc6H0T6j1YDczO0s0xLKv4ySvCBmV3HiUwKDRsTumRrTuW/kg+y0xw7JGpegkdBc/4Xf7dL9zJTKQo1RKpHT5PySbcKuOpUwmGNleuxfnGl7XBL2EMGTNptbEvvaS8p5szEoxUpbof3ENqHEbd03FBXbtcgqTBaBVCq4gbtGEEBo9pPOfQ8rpjPjqMf7hkOESHf9w+9izEfE3Bud+AKHqkmZxBxlOsnOsca3nGULdxmsagyq6n26CmhmZMYcIuhzB/E84uljBlLg0asSey0VXsRATRc7NzH7X8QQwots3JFKWL/UPD44vC0JD0tpPmqHnOLfTSl7DFe5L4DYTvhy2+5EYNgtc0D2C7mlaNUCgc422mSRgf5J3d9R5JsBCQNR2Jqox1OZffY/94Vw5ZA5Hn+24OTOzNCxKj29CIhFnQpBRc2YHiq1cDT/UDKwgU/98mW2ZZVIgdy/c3OhL/QhThT+HO4oE1t30="
